source 'https://rubygems.org'

gem 'capybara', '~> 3.0'
gem "selenium-webdriver"
gem 'cucumber', '3.1.2'
gem 'rspec'
gem 'sinatra'
gem 'rest-client'
gem 'json', '~> 1.8.6', '>= 1.8.6'
gem 'rake', '~> 13.0.3  '
gem 'byebug', '~> 8.2', '>= 8.2.2'
gem 'parallel', '1.12.1'
gem 'capybara-screenshot'
gem 'multipart-post', '~> 2.0'
gem 'os'
gem 'parallel_tests', '2.19.0'
gem 'regex'
gem 'multipart_body'
gem 'certified'
gem 'rubysl-securerandom', '~> 2.0'
gem 'spreadsheet'
gem 'sendgrid-ruby'
gem 'unicode_utils'
gem 'report_builder'
gem 'rubyXL'
gem 'pry'
gem 'webdrivers'